INSERT INTO bookscollection (booksName,links,Author,collectionId) VALUES ('System Software & Compiler Design','https://static.kopykitab.com/image/cache/data/faculty-notes/504098-300x380.jpg','VTU',1);

Insert into bookscollection (booksName,links,Author,collectionId) values('DBATU SEM IV Computer Engineering','https://www.pragationline.com/wp-content/uploads/2020/02/DG-DBATU-CO-24.jpg','Nirali Publication',2);
Insert into bookscollection (booksName,links,Author,collectionId) values('Gate Study Material','https://static.kopykitab.com/image/cache/data/faculty-notes/501178-300x380.jpg','I.C.E',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Data Structure Using c','https://www.ikbooks.com/uploads/BookImages/ikbooks-size120/9789386768384.jpg','Ankit k Ahlawat',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Computer Science Illuminated','https://images-na.ssl-images-amazon.com/images/I/41MIIDToqhL.jpg','Nelle Dale',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Electromagnetic Fields and waves','https://www.mheducation.co.in/media/catalog/product/cache/c4ff4138069c2990c9ea301d71fa9d2c/9/7/9789390385447.jpeg','Iman M Salama ',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('U-I Foundations of Cryptography','https://static.kopykitab.com/image/cache/data/faculty-notes/501933-161x244.jpg','VTU',2);
Insert into bookscollection (booksName,links,Author,collectionId) values('Design of Machine Elements','https://www.ikbooks.com/uploads/BookImages/ikbooks-size120/9788194867661.jpg','T krishna Rao',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Quantum Series','https://i.pinimg.com/originals/46/11/af/4611af80af4f8e9757b1ce595e89cfb8.jpg','Quantum Series',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('ANSI','https://aspiringcoders.com/wp-content/uploads/2020/10/Programming-ANSI-C-E.jpg','Aspiring Coders',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Mathematics-1','https://www.vikaspublishing.com/uploads/bookimages/vikas-bookscollection/9789352718832.jpg','Vikas Publication',2);
Insert into bookscollection (booksName,links,Author,collectionId) values('Practical Programming','https://kbazar.s3.amazonaws.com/__sized__/products/practical_programming-thumbnail-510x510-70.jpg','Jenifer Campbell',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Chemical Engineering Design','https://5.imimg.com/data5/RU/UB/GLADMIN-4755675/chemical-engineering-500x500.png','R K Sinnot',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Basics of Mechanical Engineering','https://inteng-storage.s3.amazonaws.com/img/iea/94w5rb9Oov/basics-of-mechanical-engineering.jpeg','Rishi Singhal',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Basic Electrical Engineering','https://kbazar.s3.amazonaws.com/__sized__/products/IMG-20200912-WA0047-thumbnail-540x540-70.jpg','D P Kothari',2);
Insert into bookscollection (booksName,links,Author,collectionId) values('Engineering Physics','https://kbazar.s3.amazonaws.com/__sized__/products/1608890145224-thumbnail-540x540-70.jpg','P.G. Kshirsagar',2);
Insert into bookscollection (booksName,links,Author,collectionId) values('Jet & Turbines','https://inteng-storage.s3.amazonaws.com/images/DECEMBER/sizes/the-devlopment-of-jet-turbine-bill-gunston_resize_md.jpg','Bill Gunston',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Objective Electrical Engineering','http://blog.bookswagon.com/wp-content/uploads/2018/08/engineering-bookscollection-online.jpg','GKP',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Cosmos','https://fivebooks.com/app/uploads/bookscollection/BC_0345539435.jpg','Ann Druyan',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Introduction to Chemical Engineering','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxqGZjGv6anF1WmbwbyFFdTk3rLlyABx_yKg&usqp=CAU','UCHE NNAJI',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Electrical Systems Design','https://www.ikbooks.com/uploads/BookImages/ikbooks-size120/9789390620135.jpg','M.K. Giridharan',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Practical Electrical Engineering','https://freepdf-bookscollection.com/doc-images/19554.png','Sergey N Makarov',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Engineering Mechanics','https://www.geniuspublications.com/uploads/book/medium_thumb/085b9b2e4b8e405367bfdbc3af12f314.jpg','A.K. Raghunath',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Industrial Engineering','https://www.pragationline.com/wp-content/uploads/2019/12/N4561.jpg','Vinod Thombre',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Electrical Engineering Handbook','https://tiimg.tistatic.com/fp/1/001/605/engineering-bookscollection-564-w410.jpg','Richard C dorf',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Objective Civil Engineering','https://www.jalarambookstore.com/v/image/product//PD_202002061919052.jpg','R Gupta',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Highway Engineering','https://easyengineering.net/wp-content/uploads/2018/01/51xOGF8TGyL._.jpg','Dr. Pathak',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Fundamentals of Electronics','https://www.ikbooks.com/uploads/BookImages/ikbooks-size120/9789385909245.jpg','Ernest M Kim',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Cracking the Coding Interview','https://www.interviewbit.com/blog/wp-content/uploads/2022/01/Cracking-the-Coding-Interview-1.jpg','Gayle Lakman',2);
Insert into bookscollection (booksName,links,Author,collectionId) values('Fluid Mechanics','https://secure-ecsd.elsevier.com/covers/80/Tango2/large/9780444986689.jpg','Elemer Bobok',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Naval Architecture','https://m.media-amazon.com/images/I/51iTBZpgffL._SL500_.jpg','Erric C Tupper',1);
Insert into bookscollection (booksName,links,Author,collectionId) values('Process Heat Transfer','https://www.elsevier.com/__data/assets/image/0003/261489/9780123971951.jpg','Robert W Smith',1);
